[package]
name = "rust-onnx-trial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = "0.7.2"
candle-onnx = "0.7.2"
ndarray = "0.16.1"
opencv = "0.93.1"
ort = "=2.0.0-rc.6"
